# Generated by Django 6.0.1 on 2026-03-09 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=3)),
                ('string_number', models.IntegerField()),
                ('fret_number', models.IntegerField()),
                ('correct', models.BooleanField()),
                ('game_mode', models.CharField(choices=[('identify', 'Identify Note'), ('find', 'Find Note')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_games_played', models.IntegerField(default=0)),
                ('preferred_filter', models.TextField(default='all')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoteStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=3)),
                ('total_attempts', models.IntegerField(default=0)),
                ('correct_attempts', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('last_attempted', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['note'],
                'unique_together': {('user', 'note')},
            },
        ),
        migrations.CreateModel(
            name='PositionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_number', models.IntegerField()),
                ('fret_number', models.IntegerField()),
                ('total_attempts', models.IntegerField(default=0)),
                ('correct_attempts', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'string_number', 'fret_number')},
            },
        ),
    ]
