# Generated by Django 6.0.1 on 2026-03-10 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeStepProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.IntegerField(default=1)),
                ('step1_note_completions', models.TextField(default='{}')),
                ('step1_current_note', models.CharField(default='', max_length=3)),
                ('step1_current_streak', models.IntegerField(default=0)),
                ('step2_notes_done', models.TextField(default='[]')),
                ('step3_notes_done', models.TextField(default='[]')),
                ('step4_completed', models.BooleanField(default=False)),
                ('step5_completed', models.BooleanField(default=False)),
                ('step6_current_bpm', models.IntegerField(default=40)),
                ('step6_completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='step_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyPracticeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('exercises_completed', models.TextField(default='[]')),
                ('total_minutes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
