# Generated by Django 6.0.1 on 2026-03-10 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_practicestepprogress_dailypracticelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreakRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak', models.IntegerField()),
                ('game_mode', models.CharField(choices=[('identify', 'Identify Note'), ('find', 'Find Note')], max_length=20)),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-streak', '-achieved_at'],
            },
        ),
    ]
